config.yaml, schema.graphql, src/EventHandlers/Pool.ts, src/EventHandlers/Voter.ts
Adds burns and mints to the indexer. Also adds voted events.
- Ran locally with envio and did verify is working in Hasura query.
=> Feature: Capture Burns and Mints

package.json, pnpm-lock.yaml
packed with the best:
https://github.com/enviodev/hyperindex/releases/tag/v2.4.0
=> Bump version

config.yaml, schema.graphql, src/EventHandlers/CLPool.ts, src/EventHandlers/NFPM.ts, src/EventHandlers/Pool.ts
Adds tracking transaction hashes in both the mint and the transfer events to link the actual user receiving the concentrated liquidity position.
Checked hashura and can confirm the new tables and transaction hashes are populating.
=> Feature: Adding concentrated liquidity mint and transaction hashes.

src/EventHandlers/Pool.ts, test/Pool.test.ts
Adds tests for pool swap event and removes error throw for non-whitelisted tokens.
=> Bugfix: Pool Event Swap to exclude whitelisted tokens.

pnpm-lock.yaml, src/EventHandlers/Pool.ts, src/EventHandlers/PoolFactory.ts, src/EventHandlers/VotingReward.ts
This code now makes use of loaders: https://docs.envio.dev/docs/HyperIndex/loaders
to improve performance
=> Adding loaders to improve historic sync speed

src/EventHandlers/Pool.ts
Remove this error log and lower it to log level.
=> Bugfix: Log missing token event but don't error.

schema.graphql, src/EventHandlers/Voter.ts, src/PriceOracle.ts, test/PriceOracle.test.ts, test/Voter.test.ts
Adds a new field in tokens to capture whitelisted events.
=> Feature: Log whitelisted events on token data.

src/Aggregators/CLPoolAggregator.ts, src/Aggregators/LiquidityPoolAggregator.ts, src/EventHandlers/Pool.ts, test/EventHandlers/Pool/Sync.test.ts
Persist Total Liquidity by keeping value in the pool snapshot.
=> Bugfix: Persist Total Liquidity

src/EventHandlers/Voter.ts, src/Store.ts
Remove lowercasing of addresses and force checksum on gauge addresses.
=> Bugfix: Force checksum addresses on gauge cache.

src/EventHandlers/Voter.ts, src/EventHandlers/VotingReward.ts
Setup emissions to log regarless of gauge pool mapping. Also use Promise.all for parallel async calls.
=> Feature: Cleanup emissions/bribes handlers

src/Constants.ts, src/PriceOracle.ts
Adds Price Oracle deployment contract for Mode. Previously was added with the wrong contract.
=> Bugfix: Price oracle mode

src/EventHandlers/CLPool.ts, src/constants/liskWhitelistedTokens.json, test/EventHandlers/CLPool/CLPool.test.ts
Adding whitelisted tokens and cleaning up cl pool.
=> Feature: Add More Lisk Whitelisted

src/EventHandlers/CLPool.ts, test/EventHandlers/CLPool/CLPool.test.ts
Adds swap deltas for reserve amounts.
=> Feature: CL Pool Swap counts with Reserves

src/Constants.ts
Changes the startblock to the oracle creation block for List.
=> Bugfix: Update List oracle start block.

src/EventHandlers/CLPool.ts, test/EventHandlers/CLPool/CLPool.test.ts
Adding a slight update to reserves with collect reserves also being computed in the count.
=> Feature: Add fee collection to reserve counts.

src/EventHandlers/Pool.ts, test/EventHandlers/CLPool/CLPool.test.ts, test/EventHandlers/Pool/Fees.test.ts
Stores standard pool reserves as nominal token values, and cleans up tests.
=> Refactor: V2 Pools Fees

src/EventHandlers/CLFactory.ts, src/EventHandlers/PoolFactory.ts, src/Helpers.ts
Update CL pool names to include tickspacing.
=> Feature: Update CL Pool Names

README.md
Includes pnpm information in readme.
=> Docs: Include pnpm in readme.

src/EventHandlers/VotingReward.ts, src/PriceOracle.ts, test/EventHandlers/VotingReward.test.ts
Fetch single bribe reward prices when a reward is generated.
=> Feature: Fetch bribe reward prices.

test/EventHandlers/SuperchainCLFactory/RootPoolCreated.test.ts, test/EventHandlers/SuperchainPoolFactory/RootPoolCreated.test.ts
Adding Superchain Factories tests.
=> Feature: Adds Superchain Factories Tests.

config.yaml, src/EventHandlers/Voter/SuperchainLeafVoter.ts, src/EventHandlers/Voter/Voter.ts, src/EventHandlers/Voter/common.ts, test/EventHandlers/SuperchainLeafVoter.test.ts, test/EventHandlers/Voter.test.ts
Updates superchain voter event capturing handlers to the correct contract signature.
https://linear.app/velodrome/issue/DATA-154/fix-superchain-gauge-events-in-enviometabase
=> Feature: Adding SuperchainVoter event capture

src/Constants.ts
Add correct RPC calls for Lisk.
=> Fix Lisk/Mode RPC

.env.example, package.json, pnpm-lock.yaml, scripts/generate_whitelist.ts, src/Constants.ts, src/Erc20.ts, src/EventHandlers/SuperchainPoolFactory.ts, src/EventHandlers/Voter/SuperchainLeafVoter.ts, src/EventHandlers/Voter/Voter.ts, src/EventHandlers/Voter/common.ts, src/PriceOracle.ts, test/PriceOracle.test.ts
=> Bugfix: Moving RPC calls to loader.

schema.graphql, src/EventHandlers/VotingReward.ts
Add pool address to voting incentives data.
=> Feature: Link Pool Address to Voting Incentives data.

package.json, src/EventHandlers/CLFactory.ts, src/EventHandlers/PoolFactory.ts, src/EventHandlers/Voter/SuperchainLeafVoter.ts, src/EventHandlers/Voter/Voter.ts, src/EventHandlers/VotingReward.ts
Adding try catch for token detail fetchers.
=> Bugfix: Catch Viem Token Detail Exceptions

package.json, src/EventHandlers/CLFactory.ts, src/EventHandlers/CLPool.ts, src/EventHandlers/Pool.ts, src/EventHandlers/PoolFactory.ts, src/PriceOracle.ts, test/EventHandlers/CLPool/CLPool.test.ts, test/EventHandlers/Pool/Swap.test.ts, test/EventHandlers/Pool/common.ts, test/EventHandlers/PoolFactory.test.ts, test/PriceOracle.test.ts
* Adding new price oracle tests and token price refresh.
* Update pool swaps to refresh token price.
* Update CL Pool to refreshTokenPrices.
* Cleanup.
* Create token entities if necessary on pool create.
=> Feature: Price Tokens on Swap (#229)

src/Constants.ts, src/EventHandlers/CLPool.ts, src/EventHandlers/NFPM.ts, src/EventHandlers/Pool.ts, src/EventHandlers/Voter/SuperchainLeafVoter.ts, src/EventHandlers/Voter/Voter.ts, src/EventHandlers/VotingReward.ts, src/PriceOracle.ts, src/constants/price_connectors.json, test/EventHandlers/SuperchainLeafVoter.test.ts, test/EventHandlers/Voter.test.ts, test/EventHandlers/VotingReward.test.ts, test/PriceOracle.test.ts
* Update PriceOracle's read prices to return a single address.
* Removing set_whitelisted_prices.
* Removing token fetch for connectors.
=> Bump Indexer

package.json, pnpm-lock.yaml, src/EventHandlers/Voter/SuperchainLeafVoter.ts, src/EventHandlers/Voter/Voter.ts
Adds registration of both fee and bribe voting rewards for the Voter contract.
=> Bugfix: Adding fee voting reward contract registration.

schema.graphql, src/EventHandlers/CLFactory.ts, src/EventHandlers/CLPool.ts, src/EventHandlers/Gauge.ts, src/EventHandlers/NFPM.ts, src/EventHandlers/Pool.ts, src/EventHandlers/PoolFactory.ts, src/EventHandlers/SuperchainCLFactory.ts, src/EventHandlers/SuperchainPoolFactory.ts, src/EventHandlers/VeNFT.ts, src/EventHandlers/Voter/SuperchainLeafVoter.ts, src/EventHandlers/Voter/Voter.ts, src/EventHandlers/VotingReward.ts, test/Aggregators/VeNFTAggregator.test.ts, test/EventHandlers/VeNFT.test.ts
Adds blocknum and log index to all non-aggregator entities.
=> Feature: Block Numbers and Log Indexes

config.yaml, schema.graphql, src/EventHandlers/ERC20.ts
Adding tracking of velo and aero reward tokens transfers on all chains.
=> Feature: Token Transfers

schema.graphql, src/EventHandlers/NFPM.ts
Fixes Voter and Gauge events to V2 contracts only.
[DATA-214](https://linear.app/velodrome/issue/DATA-214/clean-up-voter-and-gauge-contracts-in-metabase-indexer)
=> Add NFPM events.

config.yaml
Adds Metal L2 hypersync address.
=> Fix Metal L2 hypersync address

config.yaml
Update chain ID for Soneium to correct value.
=> Bugfix: Soneium 

src/Aggregators/LiquidityPoolAggregator.ts, src/EventHandlers/CLPool.ts
Adds GADT assertions for CL Pool Swaps.
=> QA: Refactor cl swaps types

src/EventHandlers/Gauge.ts, src/EventHandlers/Voter/SuperchainLeafVoter.ts, src/EventHandlers/Voter/Voter.ts
#Description
Adds both gauge registry to voters to capture each regardless of gauge type.
=> Feature: Adding gauge registry to voters.

config.yaml, schema.graphql, src/EventHandlers/DynamicFeeSwapModule.ts
Adding dynamic fee parameter capture.
=> Feature: Dynamic Fee parameters

config.yaml, src/EventHandlers/FactoryRegistry.ts, src/EventHandlers/Voter/Voter.ts
- Removes the CL and Pool Factory registrations and hard sets them.
- Uses event to register appropriate gauges based on pool type.
=> Bugfix: Dynamic Gauge Registration

config.yaml, src/EventHandlers/Voter/Voter.ts
* Add back CL and Pool Factories.
* Store Factory Registry events only and fix pool factory contracts.
* Add correct event handling.
=> Bump Deployment

config.yaml
Adding superchain addresses to ALM for tracking.
=> Feature: ALM Superchain

package.json, src/PriceOracle.ts, test/Aggregators/LiquidityPoolAggregator.test.ts, test/EventHandlers/VotingReward.test.ts, test/PriceOracle.test.ts
Add tests and a fix to make all stable chain USD variants return $1 price.
=> Bugfix: Fix USDC price for all chains.

schema.graphql, src/EventHandlers/Pool.ts
Adding pool fees event capturing.
=> Feature: Track Raw Pool Fees Events

package.json, test/Aggregators/LiquidityPoolAggregator.test.ts, test/EventHandlers/VotingReward.test.ts
Fixing flaky tests. Stubbing out external contract data calls.
=> Bugfix: Fixing Flaky Tests

config.yaml, schema.graphql, src/EventHandlers/ALM/LPWrapper.ts
Adding ALM supply Limit Cap data.
=> Feature: Add ALM Supply Limit Update Events

config.yaml, package.json, src/Constants.ts, src/constants/price_connectors.json
Add Celo indexing.
Has a hack to a fix the issue in wevm/viem/issues/3539
=> Feature: Celo

src/EventHandlers/Pool.ts, src/EventHandlers/Pool/PoolSwapLogic.ts, src/Helpers.ts, test/EventHandlers/Pool/PoolSwapLogic.test.ts
Implements:
- Same refactoring pattern to `PoolSwap` event handler
- Centralises `updateTokenData` on `Helpers.ts`. Will in future PRs include this function in other event handlers
=> `PoolSwap` event handler refactoring + `updateTokenData` centralisation

src/EventHandlers/Pool.ts, src/EventHandlers/Pool/PoolSyncLogic.ts, src/Helpers.ts, test/EventHandlers/Pool/PoolSyncLogic.test.ts
Implements:
- Same refactoring pattern to `PoolSync` event handler + tests
=> `PoolSync` event handler refactoring

config.yaml, src/EventHandlers/CLFactory.ts, src/EventHandlers/CLPool.ts, src/EventHandlers/Pool.ts, src/EventHandlers/PoolFactory.ts, src/EventHandlers/SuperchainPoolFactory.ts, src/EventHandlers/VeNFT.ts, src/EventHandlers/Voter/SuperchainLeafVoter.ts, src/EventHandlers/Voter/Voter.ts, src/EventHandlers/VotingReward.ts, src/Pools/common.ts, test/Aggregators/LiquidityPoolAggregator.test.ts, test/Aggregators/VeNFTAggregator.test.ts, test/PriceOracle.test.ts
closes #352 
Implements:
- Refactor codebase to be compatible with `preLoad`
- Left some backwards compatibility so that the PR doesn't become even bigger
=> Implementing envio's new feature - `preLoad` optimisation
